### PR TITLE
remove unsuitables and fix few mistakes

### PR DESCRIPTION
**Pull request by deabb**
removed some stuff unsuitable to be inside a timer plugin and fixed some tiny mistakes in the new code

### CODE REVIEW

**Comment by rcnoob** [comment]
is there another plugin for fov (and saving fov prefs)? i feel its fairly suitable for a mainly surf/bhop timer plugin. also hi dea we miss u, thank u for kz menu :D

**Comment by NordicGamerFE** [comment]
Is there another plugin for hiding players this is something i used a lot in both csgo and cs2

**Comment by deabb** [comment]
this pr is just my private compile with few tings removed that dont really belong into the plugin anymore and just clutter up the codebase

> Is there another plugin for hiding players this is something i used a lot in both csgo and cs2

use cs2fixes hide for that

> is there another plugin for fov (and saving fov prefs)? i feel its fairly suitable for a mainly surf/bhop timer plugin. also hi dea we miss u, thank u for kz menu :D

i believe i saw something similar in the cs# discord, you can leave that in though if ppl use it

but the trigger push fix can definitely go as its been deprecated by cs#fixes and hide never really worked properly anyways

**Comment by rcnoob** [comment]
> this pr is just my private compile with few tings removed that dont really belong into the plugin anymore and just clutter up the codebase
> 
> > Is there another plugin for hiding players this is something i used a lot in both csgo and cs2
> 
> use cs2fixes hide for that
> 
> > is there another plugin for fov (and saving fov prefs)? i feel its fairly suitable for a mainly surf/bhop timer plugin. also hi dea we miss u, thank u for kz menu :D
> 
> i believe i saw something similar in the cs# discord, you can leave that in though if ppl use it
> 
> but the trigger push fix can definitely go as its been deprecated by cs#fixes and hide never really worked properly anyways

yeah trigger push is definitely broken and hide results in nothing but bug reports from people lol, but yeah for fov I think that should be left in due to a lot of people preferring a higher fov when surfing/bhopping; since its already implemented, better to not force people who may not be in the discord to implement a new plugin for fov

**Pull request closed without merging**
